// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApi.Models.Contexts;

#nullable disable

namespace RestApi.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20231029222551_ModificationRoles")]
    partial class ModificationRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("GuestEntityMovieEntity", b =>
                {
                    b.Property<int>("GuestsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoviesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GuestEntityMovieEntity");
                });

            modelBuilder.Entity("RestApi.Models.Entities.GuestEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("RestApi.Models.Entities.MovieEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("RestApi.Models.Entities.RelationEntity", b =>
                {
                    b.Property<int>("GuestsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoviesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuestEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestsId", "MoviesId");

                    b.HasIndex("GuestEntityId");

                    b.HasIndex("MovieEntityId");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("GuestEntityMovieEntity", b =>
                {
                    b.HasOne("RestApi.Models.Entities.GuestEntity", null)
                        .WithMany()
                        .HasForeignKey("GuestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestApi.Models.Entities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestApi.Models.Entities.RelationEntity", b =>
                {
                    b.HasOne("RestApi.Models.Entities.GuestEntity", null)
                        .WithMany("Relations")
                        .HasForeignKey("GuestEntityId");

                    b.HasOne("RestApi.Models.Entities.MovieEntity", null)
                        .WithMany("Relations")
                        .HasForeignKey("MovieEntityId");
                });

            modelBuilder.Entity("RestApi.Models.Entities.GuestEntity", b =>
                {
                    b.Navigation("Relations");
                });

            modelBuilder.Entity("RestApi.Models.Entities.MovieEntity", b =>
                {
                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
